services:
  back:
    container_name: bibliotech-backend
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      PG_URL: ${PG_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db

  db:
    image: postgres:16.8-alpine
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: